int32 ActuatorID
---
float64 CUR_IQ_SETTING 
float64 CUR_PROPORTIONAL 
float64 CUR_INTEGRAL      
float64 CUR_ID_SETTING    
float64 CUR_MAXSPEED      
float64 ACTUAL_CURRENT    
float64 VEL_SETTING       
float64 VEL_PROPORTIONAL  
float64 VEL_INTEGRAL      
float64 VEL_OUTPUT_LIMITATION_MINIMUM  
float64 VEL_OUTPUT_LIMITATION_MAXIMUM  
float64 ACTUAL_VELOCITY 
float64 POS_SETTING  
float64 POS_PROPORTIONAL 
float64 POS_INTEGRAL 
float64 POS_DIFFERENTIAL 
float64 POS_OUTPUT_LIMITATION_MINIMUM 
float64 POS_OUTPUT_LIMITATION_MAXIMUM 
float64 POS_LIMITATION_MINIMUM 
float64 POS_LIMITATION_MAXIMUM 
float64 HOMING_POSITION 
float64 ACTUAL_POSITION 
float64 PROFILE_POS_MAX_SPEED 
float64 PROFILE_POS_ACC 
float64 PROFILE_POS_DEC 
float64 PROFILE_VEL_MAX_SPEED 
float64 PROFILE_VEL_ACC 
float64 PROFILE_VEL_DEC 
float64 POS_OFFSET 
float64 VOLTAGE 
float64 POS_LIMITATION_SWITCH 
float64 CURRENT_SCALE  
float64 VELOCITY_SCALE 
float64 FILTER_C_STATUS 
float64 FILTER_C_VALUE  
float64 FILTER_V_STATUS 
float64 FILTER_V_VALUE  
float64 FILTER_P_STATUS 
float64 FILTER_P_VALUE  
float64 LOCK_ENERGY 
float64 ACTUATOR_TEMPERATURE 
float64 INVERTER_TEMPERATURE 
float64 ACTUATOR_PROTECT_TEMPERATURE   
float64 ACTUATOR_RECOVERY_TEMPERATURE  
float64 INVERTER_PROTECT_TEMPERATURE   
float64 INVERTER_RECOVERY_TEMPERATURE  
float64 ACTUATOR_SWITCH  
float64 FIRMWARE_VERSION 
float64 ONLINE_STATUS 
float64 SN_ID    
float64 MODE_ID  
float64 ERROR_ID 
float64 CURRENT_LIMIT  
float64 VELOCITY_LIMIT 
float64 INIT_STATE  